# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:android)
#
# platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end
#
#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
#
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end
#
#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
# end
default_platform(:android)

platform :android do
  desc "Fastlane Test: Clean project and build Debug APK"
  lane :test_build do
    # 1. Clean old build artifacts
    sh("flutter clean")

    # 2. Fetch flutter dependencies
    sh("flutter pub get")

    # 3. Build a debug APK for testing
    sh("flutter build apk --debug")

    # 4. Success message
    UI.success("Congrats! Fastlane is working perfectly with Flutter 🚀")
  end
end
